### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ammu11** [georgesung/advanced_lane_detection#4]
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp, line 11111
Traceback (most recent call last):
  File "C:\advanced_lane_detection-master\calibrate_camera.py", line 80, in <module>
    mtx, dist = calibrate_camera()
  File "C:\advanced_lane_detection-master\calibrate_camera.py", line 52, in calibrate_camera
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11111: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor

**Comment by vamshireddyp** [comment]
For the Assertion failed (scn == 3 || scn == 4) in cv::cvtColor,

Can you check whether you are reading the image or not
